# -*- coding: utf-8 -*-
"""config_gerado.py -- GERADO de lab-celula/config.json.

NAO EDITE AQUI. Edite o JSON e rode:
    python ferramentas/gerar_config.py --aplicar

Existe porque `work/` roda dentro do GitHub Actions, onde nao ha
`config.json` nem `config.py` -- e desde 18/09 o motor precisa de numeros de
FORMATO (o respiro, a legenda, o loudnorm e a cadencia do estilo cartao).
`gerar_config.py --ver` recusa quando este arquivo esta atrasado, e
`subir_render.py` o leva para o repo com o resto.

Uso:
    from config_gerado import formato_de
    f = formato_de("cartao")          # a regra inteira do estilo
"""

CONFIG = {'formato': {'beats_max': 4,
             'beats_min': 2,
             'contexto_custo_palavras': 15,
             'contexto_max_palavras': 22,
             'contexto_min_palavras': 8,
             'contrato': {'clareza': {'ativo': True, 'nota_min': 6, 'reescritas_max': 1},
                          'modo_escrita': 'cena',
                          'porta_rigida': {'ativo': True,
                                           'checagem_tentativas': 3,
                                           'conceito_tentativas': 5,
                                           'minimos_conceito': {'clareza': 8,
                                                                'fidelidade': 7,
                                                                'filmavel': 8,
                                                                'humor': 7,
                                                                'logica': 8},
                                           'minimos_roteiro': {'clareza': 8,
                                                               'consistencia': 8,
                                                               'entendeu': 8,
                                                               'fidelidade': 8,
                                                               'humor': 7},
                                           'pedido_max_chars': 1600,
                                           'regua_tentativas_contrato': 3,
                                           'roteiro_tentativas': 4,
                                           'teto_chamadas': 60}},
             'contrato_fechado': {'aderencia_min_pct': 100,
                                  'ativo': True,
                                  'cartaz_max_palavras': 6,
                                  'cartaz_min_palavras': 3,
                                  'rotulo_max_palavras': 4},
             'curta': {'beats_max': 3,
                       'beats_min': 2,
                       'dur_max_s': 16,
                       'dur_min_s': 12,
                       'falas_max': 4,
                       'falas_min': 2},
             'decisao': {'copy_max': 0.8,
                         'copy_min': 0.2,
                         'copy_passo': 0.1,
                         'copy_pct_padrao': 0.5,
                         'efeito_min': 1.5,
                         'era_desde': '2026-10-11',
                         'metrica': 'views_7d',
                         'n_min_por_lado': 15,
                         'piso_views_mediana': 1000,
                         'z_min': 1.96},
             'duplicata_max': 0.6,
             'dur_max_s': 28,
             'dur_min_s': 20,
             'efeito_uma_em': 3,
             'estado_igual': 0.6,
             'estrutura': {'4': [{'faz': 'constata o absurdo que JA aconteceu ou o que esta em '
                                         'jogo, numa afirmacao direta; nada de explicar',
                                  'janela_s': '0-2',
                                  'max_palavras': 6,
                                  'papel': 'CONFLITO',
                                  'quem': 'o outro'},
                                 {'faz': 'em 1a pessoa: o que quer e a regra torta que segue, '
                                         'com todas as letras',
                                  'janela_s': '2-7',
                                  'max_palavras': 14,
                                  'papel': 'PREMISSA',
                                  'quem': 'quem se ferra'},
                                 {'faz': 'aponta o problema concreto (um numero, um objeto) '
                                         'que a regra ignora',
                                  'janela_s': '7-13',
                                  'max_palavras': 12,
                                  'papel': 'CHOQUE',
                                  'quem': 'o outro'},
                                 {'faz': 'se ferra pela propria regra; cita algo ja dito; a '
                                         'situacao do conflito volta pior',
                                  'janela_s': '13-20',
                                  'max_palavras': 12,
                                  'papel': 'PUNCH',
                                  'quem': 'quem se ferra'}],
                           '5': [{'faz': 'constata o absurdo que JA aconteceu ou o que esta em '
                                         'jogo, numa afirmacao direta; nada de explicar',
                                  'janela_s': '0-2',
                                  'max_palavras': 6,
                                  'papel': 'CONFLITO',
                                  'quem': 'o outro'},
                                 {'faz': 'em 1a pessoa: o que quer e a regra torta que segue, '
                                         'com todas as letras',
                                  'janela_s': '2-7',
                                  'max_palavras': 14,
                                  'papel': 'PREMISSA',
                                  'quem': 'quem se ferra'},
                                 {'faz': 'aponta o problema concreto (um numero, um objeto) '
                                         'que a regra ignora',
                                  'janela_s': '7-12',
                                  'max_palavras': 12,
                                  'papel': 'CHOQUE',
                                  'quem': 'o outro'},
                                 {'faz': 'dobra a aposta: aplica a regra de novo, pior',
                                  'janela_s': '12-17',
                                  'max_palavras': 12,
                                  'papel': 'ESCALADA',
                                  'quem': 'quem se ferra'},
                                 {'faz': 'a consequencia que a regra causou, em uma frase; '
                                         'cita algo ja dito',
                                  'janela_s': '17-24',
                                  'max_palavras': 12,
                                  'papel': 'PUNCH',
                                  'quem': 'o outro'}]},
             'fala_max_palavras': 16,
             'fala_min_palavras': 5,
             'falas_max': 6,
             'falas_min': 3,
             'fim_do_conceito': True,
             'gancho_ganho': 1.6,
             'gancho_max_palavras': 6,
             'gancho_min_palavras': 3,
             'legenda_palavras': 3,
             'loudnorm': 'loudnorm=I=-9:LRA=8:TP=-1.5',
             'margem_tts': 1.15,
             'palavras_boas_por_fala': 11,
             'pausa_punch_s': 0.7,
             'pausa_trecho_s': 0.35,
             'remate_max_palavras': 12,
             'titulo_max_palavras': 8,
             'tolerancia_dur': 0.3,
             'tolerancia_dur_acima': 0.1,
             'voz_dirigida': {'ativo': True,
                              'max_chars': 2000,
                              'max_tags_por_fala': 3,
                              'modelo': 'eleven_v4',
                              'stability': 0.5,
                              'tags': ['surprised',
                                       'proud',
                                       'confident',
                                       'sighs',
                                       'serious',
                                       'nervous',
                                       'sheepish',
                                       'sarcastic',
                                       'laughs',
                                       'angry',
                                       'annoyed',
                                       'excited',
                                       'happily',
                                       'sad',
                                       'curious',
                                       'whispers',
                                       'shouting',
                                       'deadpan',
                                       'smug',
                                       'panicked',
                                       'frustrated',
                                       'relieved',
                                       'disappointed',
                                       'embarrassed',
                                       'mocking',
                                       'laughs softly',
                                       'gasps',
                                       'groans']},
             'wps': 2.6},
 'formatos': {'cartao': {'arte_nova_max': 14,
                         'beats_max': 6,
                         'beats_min': 4,
                         'cadencia_max_s': 3.0,
                         'cadencia_min_s': 1.7,
                         'cadencia_teto_s': 4.0,
                         'cenario_lavado': 0.42,
                         'contexto_custo_palavras': 15,
                         'contexto_max_palavras': 22,
                         'contexto_min_palavras': 8,
                         'contrato': {'clareza': {'ativo': True,
                                                  'nota_min': 6,
                                                  'reescritas_max': 1},
                                      'modo_escrita': 'cena',
                                      'porta_rigida': {'ativo': True,
                                                       'checagem_tentativas': 3,
                                                       'conceito_tentativas': 5,
                                                       'minimos_conceito': {'clareza': 8,
                                                                            'fidelidade': 7,
                                                                            'filmavel': 8,
                                                                            'humor': 7,
                                                                            'logica': 8},
                                                       'minimos_roteiro': {'clareza': 8,
                                                                           'consistencia': 8,
                                                                           'entendeu': 8,
                                                                           'fidelidade': 8,
                                                                           'humor': 7},
                                                       'pedido_max_chars': 1600,
                                                       'regua_tentativas_contrato': 3,
                                                       'roteiro_tentativas': 4,
                                                       'teto_chamadas': 60}},
                         'contrato_fechado': {'aderencia_min_pct': 100,
                                              'ativo': True,
                                              'cartaz_max_palavras': 6,
                                              'cartaz_min_palavras': 3,
                                              'rotulo_max_palavras': 4},
                         'copia_fiel': True,
                         'curta': {'beats_max': 3,
                                   'beats_min': 2,
                                   'dur_max_s': 16,
                                   'dur_min_s': 12,
                                   'falas_max': 4,
                                   'falas_min': 2},
                         'decisao': {'copy_max': 0.8,
                                     'copy_min': 0.2,
                                     'copy_passo': 0.1,
                                     'copy_pct_padrao': 0.5,
                                     'efeito_min': 1.5,
                                     'era_desde': '2026-10-11',
                                     'metrica': 'views_7d',
                                     'n_min_por_lado': 15,
                                     'piso_views_mediana': 1000,
                                     'z_min': 1.96},
                         'duplicata_max': 0.6,
                         'dur_max_s': 65,
                         'dur_min_s': 45,
                         'efeito_uma_em': 3,
                         'estado_igual': 0.6,
                         'estilo': 'cartao',
                         'estrutura': {'4': [{'faz': 'constata o absurdo que JA aconteceu ou o '
                                                     'que esta em jogo, numa afirmacao direta; '
                                                     'nada de explicar',
                                              'janela_s': '0-2',
                                              'max_palavras': 6,
                                              'papel': 'CONFLITO',
                                              'quem': 'o outro'},
                                             {'faz': 'em 1a pessoa: o que quer e a regra torta '
                                                     'que segue, com todas as letras',
                                              'janela_s': '2-7',
                                              'max_palavras': 14,
                                              'papel': 'PREMISSA',
                                              'quem': 'quem se ferra'},
                                             {'faz': 'aponta o problema concreto (um numero, '
                                                     'um objeto) que a regra ignora',
                                              'janela_s': '7-13',
                                              'max_palavras': 12,
                                              'papel': 'CHOQUE',
                                              'quem': 'o outro'},
                                             {'faz': 'se ferra pela propria regra; cita algo '
                                                     'ja dito; a situacao do conflito volta '
                                                     'pior',
                                              'janela_s': '13-20',
                                              'max_palavras': 12,
                                              'papel': 'PUNCH',
                                              'quem': 'quem se ferra'}],
                                       '5': [{'faz': 'constata o absurdo que JA aconteceu ou o '
                                                     'que esta em jogo, numa afirmacao direta; '
                                                     'nada de explicar',
                                              'janela_s': '0-2',
                                              'max_palavras': 6,
                                              'papel': 'CONFLITO',
                                              'quem': 'o outro'},
                                             {'faz': 'em 1a pessoa: o que quer e a regra torta '
                                                     'que segue, com todas as letras',
                                              'janela_s': '2-7',
                                              'max_palavras': 14,
                                              'papel': 'PREMISSA',
                                              'quem': 'quem se ferra'},
                                             {'faz': 'aponta o problema concreto (um numero, '
                                                     'um objeto) que a regra ignora',
                                              'janela_s': '7-12',
                                              'max_palavras': 12,
                                              'papel': 'CHOQUE',
                                              'quem': 'o outro'},
                                             {'faz': 'dobra a aposta: aplica a regra de novo, '
                                                     'pior',
                                              'janela_s': '12-17',
                                              'max_palavras': 12,
                                              'papel': 'ESCALADA',
                                              'quem': 'quem se ferra'},
                                             {'faz': 'a consequencia que a regra causou, em '
                                                     'uma frase; cita algo ja dito',
                                              'janela_s': '17-24',
                                              'max_palavras': 12,
                                              'papel': 'PUNCH',
                                              'quem': 'o outro'}]},
                         'fala_max_palavras': 16,
                         'fala_min_palavras': 5,
                         'falas_max': 16,
                         'falas_min': 8,
                         'fator_duracao': 1.45,
                         'fim_do_conceito': True,
                         'fundo': '#F4EFE4',
                         'gancho_ganho': 2.1,
                         'gancho_max_palavras': 9,
                         'gancho_min_palavras': 3,
                         'legenda_palavras': 1,
                         'loudnorm': 'loudnorm=I=-11:LRA=13:TP=-1.0',
                         'margem_tts': 1.15,
                         'max_palavras_cartao': 9,
                         'motor': 'cartao',
                         'palavras_boas_por_fala': 11,
                         'pausa_punch_s': 0.5,
                         'pausa_trecho_s': 0.3,
                         'placa_a_cada': 3,
                         'remate_max_palavras': 14,
                         'saltos_max': 3,
                         'saltos_min': 1,
                         'sem_gente_max_s': 3.0,
                         'speed_max': 1.2,
                         'titulo_max_palavras': 8,
                         'tolerancia_dur': 0.3,
                         'tolerancia_dur_acima': 0.1,
                         'voz': {'stability': 0.35, 'style': 0.45},
                         'voz_dirigida': {'ativo': True,
                                          'max_chars': 2000,
                                          'max_tags_por_fala': 3,
                                          'modelo': 'eleven_v4',
                                          'stability': 0.5,
                                          'tags': ['surprised',
                                                   'proud',
                                                   'confident',
                                                   'sighs',
                                                   'serious',
                                                   'nervous',
                                                   'sheepish',
                                                   'sarcastic',
                                                   'laughs',
                                                   'angry',
                                                   'annoyed',
                                                   'excited',
                                                   'happily',
                                                   'sad',
                                                   'curious',
                                                   'whispers',
                                                   'shouting',
                                                   'deadpan',
                                                   'smug',
                                                   'panicked',
                                                   'frustrated',
                                                   'relieved',
                                                   'disappointed',
                                                   'embarrassed',
                                                   'mocking',
                                                   'laughs softly',
                                                   'gasps',
                                                   'groans']},
                         'wps': 3.4,
                         'wps_copia': 3.1},
              'dupla': {'beats_max': 4,
                        'beats_min': 2,
                        'contexto_custo_palavras': 15,
                        'contexto_max_palavras': 22,
                        'contexto_min_palavras': 8,
                        'contrato': {'clareza': {'ativo': True,
                                                 'nota_min': 6,
                                                 'reescritas_max': 1},
                                     'modo_escrita': 'cena',
                                     'porta_rigida': {'ativo': True,
                                                      'checagem_tentativas': 3,
                                                      'conceito_tentativas': 5,
                                                      'minimos_conceito': {'clareza': 8,
                                                                           'fidelidade': 7,
                                                                           'filmavel': 8,
                                                                           'humor': 7,
                                                                           'logica': 8},
                                                      'minimos_roteiro': {'clareza': 8,
                                                                          'consistencia': 8,
                                                                          'entendeu': 8,
                                                                          'fidelidade': 8,
                                                                          'humor': 7},
                                                      'pedido_max_chars': 1600,
                                                      'regua_tentativas_contrato': 3,
                                                      'roteiro_tentativas': 4,
                                                      'teto_chamadas': 60}},
                        'contrato_fechado': {'aderencia_min_pct': 100,
                                             'ativo': True,
                                             'cartaz_max_palavras': 6,
                                             'cartaz_min_palavras': 3,
                                             'rotulo_max_palavras': 4},
                        'curta': {'beats_max': 3,
                                  'beats_min': 2,
                                  'dur_max_s': 16,
                                  'dur_min_s': 12,
                                  'falas_max': 4,
                                  'falas_min': 2},
                        'decisao': {'copy_max': 0.8,
                                    'copy_min': 0.2,
                                    'copy_passo': 0.1,
                                    'copy_pct_padrao': 0.5,
                                    'efeito_min': 1.5,
                                    'era_desde': '2026-10-11',
                                    'metrica': 'views_7d',
                                    'n_min_por_lado': 15,
                                    'piso_views_mediana': 1000,
                                    'z_min': 1.96},
                        'duplicata_max': 0.6,
                        'dur_max_s': 28,
                        'dur_min_s': 20,
                        'efeito_uma_em': 3,
                        'estado_igual': 0.6,
                        'estilo': 'dupla',
                        'estrutura': {'4': [{'faz': 'constata o absurdo que JA aconteceu ou o '
                                                    'que esta em jogo, numa afirmacao direta; '
                                                    'nada de explicar',
                                             'janela_s': '0-2',
                                             'max_palavras': 6,
                                             'papel': 'CONFLITO',
                                             'quem': 'o outro'},
                                            {'faz': 'em 1a pessoa: o que quer e a regra torta '
                                                    'que segue, com todas as letras',
                                             'janela_s': '2-7',
                                             'max_palavras': 14,
                                             'papel': 'PREMISSA',
                                             'quem': 'quem se ferra'},
                                            {'faz': 'aponta o problema concreto (um numero, um '
                                                    'objeto) que a regra ignora',
                                             'janela_s': '7-13',
                                             'max_palavras': 12,
                                             'papel': 'CHOQUE',
                                             'quem': 'o outro'},
                                            {'faz': 'se ferra pela propria regra; cita algo ja '
                                                    'dito; a situacao do conflito volta pior',
                                             'janela_s': '13-20',
                                             'max_palavras': 12,
                                             'papel': 'PUNCH',
                                             'quem': 'quem se ferra'}],
                                      '5': [{'faz': 'constata o absurdo que JA aconteceu ou o '
                                                    'que esta em jogo, numa afirmacao direta; '
                                                    'nada de explicar',
                                             'janela_s': '0-2',
                                             'max_palavras': 6,
                                             'papel': 'CONFLITO',
                                             'quem': 'o outro'},
                                            {'faz': 'em 1a pessoa: o que quer e a regra torta '
                                                    'que segue, com todas as letras',
                                             'janela_s': '2-7',
                                             'max_palavras': 14,
                                             'papel': 'PREMISSA',
                                             'quem': 'quem se ferra'},
                                            {'faz': 'aponta o problema concreto (um numero, um '
                                                    'objeto) que a regra ignora',
                                             'janela_s': '7-12',
                                             'max_palavras': 12,
                                             'papel': 'CHOQUE',
                                             'quem': 'o outro'},
                                            {'faz': 'dobra a aposta: aplica a regra de novo, '
                                                    'pior',
                                             'janela_s': '12-17',
                                             'max_palavras': 12,
                                             'papel': 'ESCALADA',
                                             'quem': 'quem se ferra'},
                                            {'faz': 'a consequencia que a regra causou, em uma '
                                                    'frase; cita algo ja dito',
                                             'janela_s': '17-24',
                                             'max_palavras': 12,
                                             'papel': 'PUNCH',
                                             'quem': 'o outro'}]},
                        'fala_max_palavras': 16,
                        'fala_min_palavras': 5,
                        'falas_max': 6,
                        'falas_min': 3,
                        'fim_do_conceito': True,
                        'gancho_ganho': 1.6,
                        'gancho_max_palavras': 6,
                        'gancho_min_palavras': 3,
                        'legenda_palavras': 3,
                        'loudnorm': 'loudnorm=I=-9:LRA=8:TP=-1.5',
                        'margem_tts': 1.15,
                        'motor': 'palito',
                        'palavras_boas_por_fala': 11,
                        'pausa_punch_s': 0.7,
                        'pausa_trecho_s': 0.35,
                        'remate_max_palavras': 12,
                        'titulo_max_palavras': 8,
                        'tolerancia_dur': 0.3,
                        'tolerancia_dur_acima': 0.1,
                        'voz_dirigida': {'ativo': True,
                                         'max_chars': 2000,
                                         'max_tags_por_fala': 3,
                                         'modelo': 'eleven_v4',
                                         'stability': 0.5,
                                         'tags': ['surprised',
                                                  'proud',
                                                  'confident',
                                                  'sighs',
                                                  'serious',
                                                  'nervous',
                                                  'sheepish',
                                                  'sarcastic',
                                                  'laughs',
                                                  'angry',
                                                  'annoyed',
                                                  'excited',
                                                  'happily',
                                                  'sad',
                                                  'curious',
                                                  'whispers',
                                                  'shouting',
                                                  'deadpan',
                                                  'smug',
                                                  'panicked',
                                                  'frustrated',
                                                  'relieved',
                                                  'disappointed',
                                                  'embarrassed',
                                                  'mocking',
                                                  'laughs softly',
                                                  'gasps',
                                                  'groans']},
                        'wps': 2.6}},
 'quadro': {'altura_alvo_px': 1150, 'max_em_cena': 2}}

FORMATO = CONFIG["formato"]
FORMATOS = CONFIG["formatos"]
QUADRO = CONFIG["quadro"]
ESTILO_PADRAO = "dupla"


def formato_de(estilo=None):
    """A regra do estilo, ja fundida com a da dupla. Estilo desconhecido cai
    na dupla, que e' o que esta no ar."""
    e = str(estilo or ESTILO_PADRAO).lower()
    f = FORMATOS.get(e) or FORMATOS.get(ESTILO_PADRAO)
    return dict(f or FORMATO)
